In [ ]:
import numpy as np

# Concatenation in numpy array

In [ ]:
array1=np.array([[1,2,3],[4,5,6],[7,8,9]])
array1


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [69]:
array1=np.array([1,2,3,4])
array2=np.array([5,6,7,8])
array3=np.concatenate((array1,array2))
array3

array([1, 2, 3, 4, 5, 6, 7, 8])

# 2D array concatenation

In [70]:
array1=np.array([[1,2,3,4],
                 [4,5,6,7],
                 [7,8,9,7]])
array2=np.array([[8,2,5,7],
                 [4,7,0,7],
                 [7,9,8,7]])

In [71]:
np.concatenate((array1,array2),axis=0)

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [7, 8, 9, 7],
       [8, 2, 5, 7],
       [4, 7, 0, 7],
       [7, 9, 8, 7]])

In [72]:
np.concatenate((array1,array2),axis=1)

array([[1, 2, 3, 4, 8, 2, 5, 7],
       [4, 5, 6, 7, 4, 7, 0, 7],
       [7, 8, 9, 7, 7, 9, 8, 7]])

# hstack and vstack

In [73]:
array1=np.array([[1,2,3,4],
                 [4,5,6,7]])
array2=np.array([[8,2,5,7]])

In [74]:
np.vstack((array1,array2))

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [8, 2, 5, 7]])

In [75]:
array3=np.array([[23],
                 [34]])


In [76]:
np.hstack((array1,array3))

array([[ 1,  2,  3,  4, 23],
       [ 4,  5,  6,  7, 34]])

# Slicing in numpy array 

In [77]:
array1=np.arange(1,11)
array1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [78]:
array=array1[3:7]
array

array([4, 5, 6, 7])

# For 2D array slicing 

In [79]:
array2=np.array([[4,5,6,7],
                 [12,23,45,67],
                 [12,32,45,66]])
array2.shape

(3, 4)

In [80]:
print(array2[1,1])

23


In [81]:
print(array2[1,3])

67


In [82]:
print(array2[2,2])

45


In [83]:
array2[1:3,1:3]

array([[23, 45],
       [32, 45]])

In [84]:
array2[0:,1:3]

array([[ 5,  6],
       [23, 45],
       [32, 45]])

# Reshaping method in numpy array 

In [85]:
array2

array([[ 4,  5,  6,  7],
       [12, 23, 45, 67],
       [12, 32, 45, 66]])

In [86]:
array2.shape

(3, 4)

In [87]:
array2.reshape(4,3)

array([[ 4,  5,  6],
       [ 7, 12, 23],
       [45, 67, 12],
       [32, 45, 66]])

In [88]:
array2.reshape(2,6)

array([[ 4,  5,  6,  7, 12, 23],
       [45, 67, 12, 32, 45, 66]])

In [89]:
array2.reshape(6,2)

array([[ 4,  5],
       [ 6,  7],
       [12, 23],
       [45, 67],
       [12, 32],
       [45, 66]])

In [90]:
array2.reshape(12)

array([ 4,  5,  6,  7, 12, 23, 45, 67, 12, 32, 45, 66])

In [91]:
array2.reshape(2,3,2)

array([[[ 4,  5],
        [ 6,  7],
        [12, 23]],

       [[45, 67],
        [12, 32],
        [45, 66]]])

In [92]:
array=np.arange(1,101)
array

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [93]:
array.reshape(20,5)

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25],
       [ 26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45],
       [ 46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55],
       [ 56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75],
       [ 76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85],
       [ 86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100]])

# Day 4

# Random array in numpy

In [94]:
# rand() gives the random value betwen 0-1
# randint() gives the random integer value in given range

In [95]:
array_1= np.random.rand(4, 6)
array_1

array([[0.69090276, 0.22449907, 0.34982893, 0.80362721, 0.59455441,
        0.85604652],
       [0.15839443, 0.41962302, 0.69980166, 0.1643003 , 0.10465691,
        0.3321517 ],
       [0.8140385 , 0.9563493 , 0.70045667, 0.93786354, 0.25281345,
        0.30795398],
       [0.69381738, 0.41363208, 0.15409231, 0.93366098, 0.8159304 ,
        0.25744642]])

In [ ]:
array_2= np.random.rand(10)
array_2

array([0.18591294, 0.60027917, 0.29030502, 0.0164344 , 0.1529492 ,
       0.50238057, 0.64398722, 0.72582628, 0.69482514, 0.81629693])

# Randint method

In [97]:
array3= np.random.randint(1,100,size=10)
array3

array([61, 12, 93, 59, 83, 68, 93, 64, 32, 94], dtype=int32)

# splitting in numpy array 

In [98]:
array1=np.random.randint(100,500,size=(10,6))
array1

array([[143, 349, 294, 444, 218, 237],
       [227, 353, 214, 399, 114, 317],
       [444, 457, 363, 113, 299, 352],
       [450, 240, 134, 213, 222, 135],
       [200, 195, 411, 187, 487, 487],
       [190, 315, 346, 170, 270, 431],
       [410, 267, 447, 102, 354, 106],
       [269, 419, 259, 385, 283, 201],
       [380, 267, 396, 313, 349, 179],
       [353, 224, 222, 384, 276, 193]], dtype=int32)

In [99]:
array1_1,array1_2=np.split(array1,2,axis=0)

In [100]:
array1_1

array([[143, 349, 294, 444, 218, 237],
       [227, 353, 214, 399, 114, 317],
       [444, 457, 363, 113, 299, 352],
       [450, 240, 134, 213, 222, 135],
       [200, 195, 411, 187, 487, 487]], dtype=int32)

In [101]:
array1_2

array([[190, 315, 346, 170, 270, 431],
       [410, 267, 447, 102, 354, 106],
       [269, 419, 259, 385, 283, 201],
       [380, 267, 396, 313, 349, 179],
       [353, 224, 222, 384, 276, 193]], dtype=int32)

In [102]:
array1_1,array1_2=np.split(array1,2,axis=1)

In [103]:
array1_1

array([[143, 349, 294],
       [227, 353, 214],
       [444, 457, 363],
       [450, 240, 134],
       [200, 195, 411],
       [190, 315, 346],
       [410, 267, 447],
       [269, 419, 259],
       [380, 267, 396],
       [353, 224, 222]], dtype=int32)

In [104]:
array1_2

array([[444, 218, 237],
       [399, 114, 317],
       [113, 299, 352],
       [213, 222, 135],
       [187, 487, 487],
       [170, 270, 431],
       [102, 354, 106],
       [385, 283, 201],
       [313, 349, 179],
       [384, 276, 193]], dtype=int32)

In [105]:
array1=np.random.randint(100,500,size=(9,6))
array1

array([[216, 355, 123, 296, 193, 159],
       [416, 240, 144, 158, 260, 257],
       [192, 321, 344, 431, 479, 454],
       [138, 174, 422, 425, 251, 300],
       [108, 490, 156, 412, 391, 367],
       [145, 250, 347, 455, 416, 136],
       [118, 402, 480, 170, 430, 402],
       [336, 282, 154, 448, 354, 465],
       [426, 353, 415, 440, 300, 219]], dtype=int32)

In [106]:
array1_1,array1_2,array1_3=np.split(array1,3,axis=0)

In [107]:
array1_1

array([[216, 355, 123, 296, 193, 159],
       [416, 240, 144, 158, 260, 257],
       [192, 321, 344, 431, 479, 454]], dtype=int32)

In [108]:
array1_2

array([[138, 174, 422, 425, 251, 300],
       [108, 490, 156, 412, 391, 367],
       [145, 250, 347, 455, 416, 136]], dtype=int32)

In [109]:
array1_3

array([[118, 402, 480, 170, 430, 402],
       [336, 282, 154, 448, 354, 465],
       [426, 353, 415, 440, 300, 219]], dtype=int32)

# colunm wise splitting

In [110]:
array1_1,array1_2,array1_3=np.split(array1,3,axis=1)

In [111]:
array1_1

array([[216, 355],
       [416, 240],
       [192, 321],
       [138, 174],
       [108, 490],
       [145, 250],
       [118, 402],
       [336, 282],
       [426, 353]], dtype=int32)

In [112]:
array1_2

array([[123, 296],
       [144, 158],
       [344, 431],
       [422, 425],
       [156, 412],
       [347, 455],
       [480, 170],
       [154, 448],
       [415, 440]], dtype=int32)

In [113]:
array1_3

array([[193, 159],
       [260, 257],
       [479, 454],
       [251, 300],
       [391, 367],
       [416, 136],
       [430, 402],
       [354, 465],
       [300, 219]], dtype=int32)

# For unequal splitting 

In [114]:
array1=np.random.randint(100,500,size=(9,6))
array1

array([[489, 179, 387, 101, 334, 372],
       [497, 485, 249, 480, 358, 383],
       [294, 141, 282, 246, 469, 185],
       [103, 316, 486, 297, 308, 177],
       [447, 287, 491, 347, 484, 114],
       [382, 313, 207, 292, 313, 453],
       [365, 476, 186, 350, 174, 358],
       [106, 281, 200, 259, 459, 124],
       [206, 389, 115, 258, 420, 199]], dtype=int32)

In [115]:
array1_1,array1_2=np.split(array1,[5],axis=1)

In [116]:
array1_1

array([[489, 179, 387, 101, 334],
       [497, 485, 249, 480, 358],
       [294, 141, 282, 246, 469],
       [103, 316, 486, 297, 308],
       [447, 287, 491, 347, 484],
       [382, 313, 207, 292, 313],
       [365, 476, 186, 350, 174],
       [106, 281, 200, 259, 459],
       [206, 389, 115, 258, 420]], dtype=int32)

In [117]:
array1_2

array([[372],
       [383],
       [185],
       [177],
       [114],
       [453],
       [358],
       [124],
       [199]], dtype=int32)

In [118]:
array1

array([[489, 179, 387, 101, 334, 372],
       [497, 485, 249, 480, 358, 383],
       [294, 141, 282, 246, 469, 185],
       [103, 316, 486, 297, 308, 177],
       [447, 287, 491, 347, 484, 114],
       [382, 313, 207, 292, 313, 453],
       [365, 476, 186, 350, 174, 358],
       [106, 281, 200, 259, 459, 124],
       [206, 389, 115, 258, 420, 199]], dtype=int32)

In [ ]:
array1_1,array1_2,array1_3=np.split(array1,[3,5],axis=1)

In [124]:
array1_1

array([[489, 179, 387],
       [497, 485, 249],
       [294, 141, 282],
       [103, 316, 486],
       [447, 287, 491],
       [382, 313, 207],
       [365, 476, 186],
       [106, 281, 200],
       [206, 389, 115]], dtype=int32)

In [121]:
array1_2

array([[101, 334],
       [480, 358],
       [246, 469],
       [297, 308],
       [347, 484],
       [292, 313],
       [350, 174],
       [259, 459],
       [258, 420]], dtype=int32)

In [125]:
array1_3

array([[372],
       [383],
       [185],
       [177],
       [114],
       [453],
       [358],
       [124],
       [199]], dtype=int32)

# Load the dataset into numpy array

In [126]:
iris_array=np.genfromtxt(r"C:\Users\User\OneDrive\Desktop\Machine_Learning\MLclass\iris.txt",delimiter=',',dtype=str)

In [ ]:
iris_array

array([['5.1', '3.5', '1.4', '0.2', 'Iris-setosa'],
       ['4.9', '3.0', '1.4', '0.2', 'Iris-setosa'],
       ['4.7', '3.2', '1.3', '0.2', 'Iris-setosa'],
       ['4.6', '3.1', '1.5', '0.2', 'Iris-setosa'],
       ['5.0', '3.6', '1.4', '0.2', 'Iris-setosa'],
       ['5.4', '3.9', '1.7', '0.4', 'Iris-setosa'],
       ['4.6', '3.4', '1.4', '0.3', 'Iris-setosa'],
       ['5.0', '3.4', '1.5', '0.2', 'Iris-setosa'],
       ['4.4', '2.9', '1.4', '0.2', 'Iris-setosa'],
       ['4.9', '3.1', '1.5', '0.1', 'Iris-setosa'],
       ['5.4', '3.7', '1.5', '0.2', 'Iris-setosa'],
       ['4.8', '3.4', '1.6', '0.2', 'Iris-setosa'],
       ['4.8', '3.0', '1.4', '0.1', 'Iris-setosa'],
       ['4.3', '3.0', '1.1', '0.1', 'Iris-setosa'],
       ['5.8', '4.0', '1.2', '0.2', 'Iris-setosa'],
       ['5.7', '4.4', '1.5', '0.4', 'Iris-setosa'],
       ['5.4', '3.9', '1.3', '0.4', 'Iris-setosa'],
       ['5.1', '3.5', '1.4', '0.3', 'Iris-setosa'],
       ['5.7', '3.8', '1.7', '0.3', 'Iris-setosa'],
       ['5.1

In [ ]:
iris_features,iris_species=np.split(iris_array,[4],axis=1)

In [ ]:
iris_features

array([['5.1', '3.5', '1.4', '0.2'],
       ['4.9', '3.0', '1.4', '0.2'],
       ['4.7', '3.2', '1.3', '0.2'],
       ['4.6', '3.1', '1.5', '0.2'],
       ['5.0', '3.6', '1.4', '0.2'],
       ['5.4', '3.9', '1.7', '0.4'],
       ['4.6', '3.4', '1.4', '0.3'],
       ['5.0', '3.4', '1.5', '0.2'],
       ['4.4', '2.9', '1.4', '0.2'],
       ['4.9', '3.1', '1.5', '0.1'],
       ['5.4', '3.7', '1.5', '0.2'],
       ['4.8', '3.4', '1.6', '0.2'],
       ['4.8', '3.0', '1.4', '0.1'],
       ['4.3', '3.0', '1.1', '0.1'],
       ['5.8', '4.0', '1.2', '0.2'],
       ['5.7', '4.4', '1.5', '0.4'],
       ['5.4', '3.9', '1.3', '0.4'],
       ['5.1', '3.5', '1.4', '0.3'],
       ['5.7', '3.8', '1.7', '0.3'],
       ['5.1', '3.8', '1.5', '0.3'],
       ['5.4', '3.4', '1.7', '0.2'],
       ['5.1', '3.7', '1.5', '0.4'],
       ['4.6', '3.6', '1.0', '0.2'],
       ['5.1', '3.3', '1.7', '0.5'],
       ['4.8', '3.4', '1.9', '0.2'],
       ['5.0', '3.0', '1.6', '0.2'],
       ['5.0', '3.4', '1.6', '0.4'],
 

In [ ]:
iris_species

array([['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-se

In [ ]:
iris_features=iris_features.astype(float)

In [ ]:
iris_features

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [ ]:
iris_features.dtype

dtype('float64')

# Mean Median and Mode

# Mean

In [ ]:
array1=np.array([12,14,16,13,10])
mean=np.mean(array1)
mean

np.float64(13.0)

In [ ]:
median=np.median(array1)
median

np.float64(13.0)

In [ ]:
standard_deviation=np.std(array1)
standard_deviation

np.float64(2.0)

In [ ]:
array2=np.array([[1,2,3],[4,5,6],[7,8,9]])
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
array2=np.random.randint(15,25,size=(6,4))
array2

array([[18, 21, 22, 23],
       [22, 15, 22, 22],
       [22, 23, 21, 21],
       [18, 15, 22, 17],
       [21, 24, 20, 18],
       [24, 23, 18, 16]], dtype=int32)

In [ ]:
mean2=np.mean(array2,axis=0)

In [ ]:
mean2

array([20.83333333, 20.16666667, 20.83333333, 19.5       ])

In [ ]:
iris_features_mean=np.mean(iris_features,axis=0)
iris_features_mean

array([5.84333333, 3.054     , 3.75866667, 1.19866667])

In [127]:
mean2=np.mean(array2,axis=1)

In [128]:
mean2

array([ 5.5 , 36.75, 38.75])