In [1]:
import numpy as np

# ARAANGE FUNCTION IN NUMPY ARRAY

In [2]:
rangearray=np.arange(1,101)
rangearray

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [3]:
oddarray=np.arange(1,101,2)
oddarray

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [4]:
evenarray=np.arange(0,101,2)
evenarray

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

# Linspace function in array

In [5]:
array=np.linspace(1,100,10)
array

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [6]:
linarray=np.linspace(1,1000,10)
linarray

array([   1.,  112.,  223.,  334.,  445.,  556.,  667.,  778.,  889.,
       1000.])

# Arithmetic operations in numpy

In [7]:
list1=[1,2,3] #adding two list
list2=[4,5,6]
list=list1+list2
list

[1, 2, 3, 4, 5, 6]

In [8]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
print(arr1+arr2)

[5 7 9]


In [9]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
print(arr1-arr2)

[-3 -3 -3]


In [10]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
print(arr1/arr2)

[0.25 0.4  0.5 ]


In [11]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
print(arr1*arr2)

[ 4 10 18]


In [12]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
print(arr1//arr2)

[0 0 0]


# For Matrix Multiplication

In [13]:
arr1=np.array([[1,3,5],[2,4,6],[7,8,9]])
arr2=np.array([[1,3,5],[2,4,6],[7,8,9]])
arr1 @ arr2

array([[ 42,  55,  68],
       [ 52,  70,  88],
       [ 86, 125, 164]])