# concatenation in numpy array

In [1]:
import numpy as np


In [2]:
ar1 = np.array([1,2,3,4])
ar2 = np.array([5,6,7,8])
ar3 = np.concatenate((ar1,ar2))


In [3]:
ar3

array([1, 2, 3, 4, 5, 6, 7, 8])

## FOR TWO DIMENSIONAL ARRAY

In [4]:
arr2d1 = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12]])
arr2d2 = np.array([[13,14,15,16],
                 [17,18,19,20],
                 [21,22,23,24]])

np.concatenate((arr2d1,arr2d2), axis = 0)



array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [5]:
np.concatenate((arr2d1,arr2d2), axis = 1)

array([[ 1,  2,  3,  4, 13, 14, 15, 16],
       [ 5,  6,  7,  8, 17, 18, 19, 20],
       [ 9, 10, 11, 12, 21, 22, 23, 24]])

## hstack and vstack

In [6]:
arr1 = np.array([[7,8,10,11],
                 [12,16,18,20]])
arr2 = np.array([[2,2,2,2]])


In [7]:
np.vstack((arr1,arr2))

array([[ 7,  8, 10, 11],
       [12, 16, 18, 20],
       [ 2,  2,  2,  2]])

In [8]:
arr3 = np.array([[23],
                 [24]])

In [9]:
np.hstack((arr1,arr3))

array([[ 7,  8, 10, 11, 23],
       [12, 16, 18, 20, 24]])

# SLICING IN NUMPY ARRAY

In [10]:
array1 = np.arange(1,11)
array1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
array2 = array1[3:7]

# FOR TWO DIMENSIONAL ARRAY

In [12]:
array2 = np.array([[4,5,6,7],
                   [12,13,14,15],
                   [18,23,25,26]])
array2.shape

(3, 4)

In [13]:
array2.ndim

2

In [14]:
print(array2[1,1])

13


In [15]:
print(array2[2,2])

25


In [16]:
print(array2[1:3,1:3])

[[13 14]
 [23 25]]


In [17]:
print(array2[0:,1:3])

[[ 5  6]
 [13 14]
 [23 25]]


### RESHAPING IN  NUMPY ARRAY

In [18]:
array2

array([[ 4,  5,  6,  7],
       [12, 13, 14, 15],
       [18, 23, 25, 26]])

In [19]:
array2.shape

(3, 4)

In [20]:
array2.reshape(4,3)

array([[ 4,  5,  6],
       [ 7, 12, 13],
       [14, 15, 18],
       [23, 25, 26]])

In [21]:
array2.reshape(2,6)

array([[ 4,  5,  6,  7, 12, 13],
       [14, 15, 18, 23, 25, 26]])

In [22]:
array2.reshape(5,2)

ValueError: cannot reshape array of size 12 into shape (5,2)

In [ ]:
array2.reshape(12)

array([ 4,  5,  6,  7, 12, 13, 14, 15, 18, 23, 25, 26])

In [ ]:
array2.reshape(2,3,2)

array([[[ 4,  5],
        [ 6,  7],
        [12, 13]],

       [[14, 15],
        [18, 23],
        [25, 26]]])

## store the element from 1 to hundred on 2d array of shape (20,5)

In [ ]:
array1 = np.arange(1,101,1)
array1

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [ ]:
array2 = array1.reshape(20,5)
array2

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25],
       [ 26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45],
       [ 46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55],
       [ 56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75],
       [ 76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85],
       [ 86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100]])